project_id = "qqvirwqrecpzbldjyiua"

[functions.og-share]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.graphy-sync]
verify_jwt = false

[functions.graphy-webhook]
verify_jwt = false
